import {createTestApiary,createTestHive,createTestUser,loginTestUser,testRequest,TestUser} from './helpers.js';
import {prisma} from './setup.js';

describe('Hive placement journal',()=>{
 let user:TestUser;let source:{id:string,name:string};let target:{id:string,name:string};let hive:{id:string;apiaryId:string};
 beforeEach(async()=>{user=await loginTestUser(await createTestUser());source=await createTestApiary(user,{name:'Heime'});target=await createTestApiary(user,{name:'Lyng'});hive=await createTestHive(source,{hiveNumber:'A1'});await prisma.hivePlacement.create({data:{hiveId:hive.id,apiaryId:source.id,startedAt:new Date('2026-01-01T00:00:00Z'),movementType:'initial',apiaryName:source.name,createdById:user.id}});});
 it('closes current placement, creates snapshot and updates cache atomically',async()=>{const res=await testRequest.post('/api/v1/placements/move').set('Authorization',`Bearer ${user.accessToken}`).set('Idempotency-Key','move-1').send({hiveId:hive.id,toApiaryId:target.id,startedAt:'2026-08-20T09:00:00.000Z',movementType:'temporary',reason:'Lyngtrekk'}).expect(201);expect(res.body.data.placement.apiaryName).toBe('Lyng');expect((await prisma.hive.findUniqueOrThrow({where:{id:hive.id}})).apiaryId).toBe(target.id);expect(await prisma.hivePlacement.count({where:{hiveId:hive.id}})).toBe(2);});
 it('replays an idempotent request without duplicates',async()=>{const body={hiveId:hive.id,toApiaryId:target.id,startedAt:'2026-08-20T09:00:00.000Z',movementType:'temporary',reason:'Lyng'};const first=await testRequest.post('/api/v1/placements/move').set('Authorization',`Bearer ${user.accessToken}`).set('Idempotency-Key','stable').send(body).expect(201);const second=await testRequest.post('/api/v1/placements/move').set('Authorization',`Bearer ${user.accessToken}`).set('Idempotency-Key','stable').send(body).expect(201);expect(second.body).toEqual(first.body);expect(await prisma.hivePlacement.count({where:{hiveId:hive.id}})).toBe(2);});
 it('rejects reuse of a key with different content',async()=>{const base={hiveId:hive.id,toApiaryId:target.id,startedAt:'2026-08-20T09:00:00.000Z',movementType:'temporary'};await testRequest.post('/api/v1/placements/move').set('Authorization',`Bearer ${user.accessToken}`).set('Idempotency-Key','reused').send(base).expect(201);const res=await testRequest.post('/api/v1/placements/move').set('Authorization',`Bearer ${user.accessToken}`).set('Idempotency-Key','reused').send({...base,reason:'different'}).expect(409);expect(res.body.error.code).toBe('IDEMPOTENCY_KEY_REUSED');});
});
