'use client';
import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { apiariesApi,complianceEventsApi,hivesApi } from '@/lib/api';
import { Card,CardContent } from '@/components/ui/card';import { Button } from '@/components/ui/button';import toast from 'react-hot-toast';
const types=[['mortality','Dødelighet'],['disease_suspicion','Sykdomsmistanke'],['biosecurity_measure','Biosikkerhetstiltak'],['cleaning_disinfection','Rengjøring/desinfeksjon'],['sample','Prøve'],['analysis_result','Analyseresultat'],['animal_health_visit','Dyrehelsebesøk'],['official_control','Offentlig kontroll'],['authority_notification','Varsling'],['other','Annet']];
export default function CompliancePage(){const qc=useQueryClient();const[eventType,setType]=useState('mortality');const[apiaryId,setApiary]=useState('');const[hiveId,setHive]=useState('');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[extra,setExtra]=useState<Record<string,string>>({});const{data:events}=useQuery({queryKey:['compliance'],queryFn:()=>complianceEventsApi.list()});const{data:apiaries}=useQuery({queryKey:['apiaries'],queryFn:()=>apiariesApi.list()});const{data:hives}=useQuery({queryKey:['hives'],queryFn:()=>hivesApi.list()});const create=useMutation({mutationFn:()=>{const normalized={...extra};for(const key of ['sampleTakenAt','resultReceivedAt','notifiedAt'])if(normalized[key])normalized[key]=new Date(normalized[key]).toISOString();return complianceEventsApi.create({eventType,apiaryId:apiaryId||undefined,hiveId:hiveId||undefined,occurredAt:new Date().toISOString(),title,description:description||undefined,...normalized,mortalityCount:extra.mortalityCount?Number(extra.mortalityCount):undefined});},onSuccess:()=>{toast.success('Hendelse lagret');setTitle('');qc.invalidateQueries({queryKey:['compliance']});},onError:(e:any)=>toast.error(e?.error?.message||'Kunne ikke lagre')});
 const field=(name:string,label:string,type='text')=><input className="border rounded p-2" type={type} placeholder={label} value={extra[name]||''} onChange={e=>setExtra({...extra,[name]:e.target.value})}/>;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Helse, biosikkerhet og kontroll</h1><p className="text-gray-500">Strukturert journal for hendelser som krever oppfølging.</p></div>{eventType==='disease_suspicion'&&<div className="bg-red-50 border border-red-200 text-red-800 p-4 rounded">Registrering i Birøkt varsler ikke Mattilsynet. Kontakt Mattilsynet umiddelbart dersom varslingsplikt kan foreligge.</div>}<Card><CardContent className="pt-6 grid gap-3"><select className="border rounded p-2" value={eventType} onChange={e=>{setType(e.target.value);setExtra({});}}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="grid md:grid-cols-2 gap-3"><select className="border rounded p-2" value={apiaryId} onChange={e=>setApiary(e.target.value)}><option value="">Bigård</option>{(apiaries?.data||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="border rounded p-2" value={hiveId} onChange={e=>setHive(e.target.value)}><option value="">Kube</option>{(hives?.data||[]).map((x:any)=><option key={x.id} value={x.id}>{x.hiveNumber}</option>)}</select></div><input className="border rounded p-2" placeholder="Tittel" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="border rounded p-2" placeholder="Beskrivelse / utført tiltak" value={description} onChange={e=>setDescription(e.target.value)}/>{eventType==='mortality'&&field('mortalityCount','Antall døde','number')}{eventType==='sample'&&<>{field('sampleReference','Prøvereferanse')}{field('sampleTakenAt','Prøvetakingstid','datetime-local')}</>}{eventType==='analysis_result'&&<>{field('sampleReference','Prøvereferanse')}{field('analysisType','Analysetype')}{field('analysisResult','Resultat')}{field('resultReceivedAt','Resultat mottatt','datetime-local')}</>}{eventType==='animal_health_visit'&&field('professionalName','Person/virksomhet')}{eventType==='official_control'&&<>{field('authorityName','Myndighet')}{field('authorityReference','Referanse')}</>}{eventType==='authority_notification'&&<>{field('authorityName','Myndighet')}{field('notifiedAt','Varslet tidspunkt','datetime-local')}</>}<Button disabled={!title||(!apiaryId&&!hiveId)||create.isPending} onClick={()=>create.mutate()}>Lagre hendelse</Button></CardContent></Card><div className="space-y-2">{(events?.data||[]).map((x:any)=><Card key={x.id}><CardContent className="py-4"><b>{x.title}</b><div className="text-sm text-gray-500">{new Date(x.occurredAt).toLocaleString('nb-NO')} · {x.eventType}</div><p>{x.description}</p></CardContent></Card>)}</div></div>}
