import { Router } from 'express';
import { z } from 'zod';
import { authenticate } from '../middleware/auth.js';
import { validateBody, validateParams, validateQuery } from '../middleware/validate.js';
import prisma from '../utils/prisma.js';
import { addCalendarYears, auditData } from '../services/complianceService.js';
import { calculatePagination, ErrorCodes, sendError, sendSuccess } from '../utils/response.js';
import { hiveAccess } from '../services/accessService.js';

const router=Router();router.use(authenticate);
const source=z.object({productionId:z.string().uuid(),hiveId:z.string().uuid(),sourceQuantityKg:z.number().positive().finite().optional()});
const createSchema=z.object({batchNumber:z.string().trim().min(1).max(100),productType:z.string().trim().min(1).max(100),harvestStartedAt:z.string().datetime({offset:true}),harvestEndedAt:z.string().datetime({offset:true}).optional(),totalQuantityKg:z.number().positive().finite().optional(),moisturePercent:z.number().min(0).max(100).optional(),notes:z.string().trim().max(5000).optional(),sources:z.array(source).min(1).max(100)});
const updateSchema=z.object({baseVersion:z.number().int().positive(),reason:z.string().trim().min(1),totalQuantityKg:z.number().positive().finite().optional(),moisturePercent:z.number().min(0).max(100).optional(),notes:z.string().trim().max(5000).nullable().optional()});
const decisionSchema=z.object({reason:z.string().trim().min(1).max(1000)});const idSchema=z.object({id:z.string().uuid()});
const listSchema=z.object({page:z.string().transform(Number).pipe(z.number().int().min(1)).default('1'),perPage:z.string().transform(Number).pipe(z.number().int().min(1).max(100)).default('20'),includeVoided:z.string().transform(v=>v==='true').optional()});

async function warnings(batchId:string){
  const batch=await prisma.productionBatch.findUnique({where:{id:batchId},include:{sources:true}});if(!batch)return[];
  const hiveIds=batch.sources.map(s=>s.hiveId);
  const treatments=await prisma.treatment.findMany({where:{hiveId:{in:hiveIds},voidedAt:null,startDate:{lte:batch.harvestEndedAt??batch.harvestStartedAt},OR:[{withholdingEndDate:null},{withholdingEndDate:{gte:batch.harvestStartedAt}}]}});
  return treatments.map(t=>({code:'TREATMENT_HARVEST_OVERLAP',hiveId:t.hiveId,treatmentId:t.id,message:'Registrert behandling overlapper høsting eller tilbakeholdelsestid. Må vurderes faglig.'}));
}
router.get('/',validateQuery(listSchema),async(req,res)=>{const{page,perPage,includeVoided}=req.query as any;const where={userId:req.user!.id,...(!includeVoided&&{voidedAt:null})};const[total,rows]=await Promise.all([prisma.productionBatch.count({where}),prisma.productionBatch.findMany({where,include:{sources:true},orderBy:{harvestStartedAt:'desc'},skip:(page-1)*perPage,take:perPage})]);sendSuccess(res,rows,200,calculatePagination(page,perPage,total));});
router.post('/',validateBody(createSchema),async(req,res)=>{
 const userId=req.user!.id;try{const row=await prisma.$transaction(async tx=>{const harvestStart=new Date(req.body.harvestStartedAt);const created=await tx.productionBatch.create({data:{userId,batchNumber:req.body.batchNumber,productType:req.body.productType,harvestStartedAt:harvestStart,harvestEndedAt:req.body.harvestEndedAt?new Date(req.body.harvestEndedAt):null,totalQuantityKg:req.body.totalQuantityKg,moisturePercent:req.body.moisturePercent,notes:req.body.notes,retentionUntil:addCalendarYears(req.body.harvestEndedAt?new Date(req.body.harvestEndedAt):harvestStart)}});for(const item of req.body.sources){const production=await tx.production.findUnique({where:{id:item.productionId}});const access=await hiveAccess(userId,item.hiveId,tx);if(!production||production.userId!==userId||!access)throw Object.assign(new Error('Invalid or inaccessible production source'),{status:422});if(production.hiveId&&production.hiveId!==item.hiveId)throw Object.assign(new Error('Source hive does not match production record'),{status:422});await tx.productionBatchSource.create({data:{productionBatchId:created.id,productionId:production.id,hiveId:item.hiveId,hiveNumberSnapshot:access.hive.hiveNumber,apiaryNameSnapshot:access.hive.apiary.name,sourceQuantityKg:item.sourceQuantityKg}});}await tx.auditLog.create({data:auditData({userId,entityType:'ProductionBatch',entityId:created.id,action:'create',after:created,requestId:res.locals.requestId})});return created;});sendSuccess(res,{...row,warnings:await warnings(row.id)},201);}catch(e){const x=e as any;sendError(res,ErrorCodes.VALIDATION_ERROR,x.message,x.status??422);}
});
router.get('/:id',validateParams(idSchema),async(req,res)=>{const row=await prisma.productionBatch.findFirst({where:{id:req.params.id,userId:req.user!.id},include:{sources:{include:{production:true}}}});if(!row){sendError(res,ErrorCodes.NOT_FOUND,'Production batch not found',404);return;}sendSuccess(res,{...row,warnings:await warnings(row.id)});});
router.put('/:id',validateParams(idSchema),validateBody(updateSchema),async(req,res)=>{const userId=req.user!.id;try{const row=await prisma.$transaction(async tx=>{const before=await tx.productionBatch.findFirst({where:{id:req.params.id,userId}});if(!before)throw Object.assign(new Error('Not found'),{status:404,code:ErrorCodes.NOT_FOUND});if(before.version!==req.body.baseVersion)throw Object.assign(new Error('Version conflict'),{status:409,code:ErrorCodes.VERSION_CONFLICT});const updated=await tx.productionBatch.update({where:{id:before.id},data:{totalQuantityKg:req.body.totalQuantityKg,moisturePercent:req.body.moisturePercent,notes:req.body.notes,version:{increment:1}}});await tx.auditLog.create({data:auditData({userId,entityType:'ProductionBatch',entityId:before.id,action:'update',before,after:updated,reason:req.body.reason,requestId:res.locals.requestId})});return updated;});sendSuccess(res,row);}catch(e){const x=e as any;sendError(res,x.code??ErrorCodes.INTERNAL_ERROR,x.message,x.status??500);}});
for(const [path,status] of [['release','released'],['hold','held'],['discard','discarded']] as const){router.post(`/:id/${path}`,validateParams(idSchema),validateBody(decisionSchema),async(req,res)=>{const userId=req.user!.id;const before=await prisma.productionBatch.findFirst({where:{id:req.params.id,userId}});if(!before){sendError(res,ErrorCodes.NOT_FOUND,'Production batch not found',404);return;}if(status==='released'){const count=await prisma.productionBatchSource.count({where:{productionBatchId:before.id}});if(!count){sendError(res,ErrorCodes.VALIDATION_ERROR,'Release requires explicit hive sources',422);return;}}const row=await prisma.$transaction(async tx=>{const updated=await tx.productionBatch.update({where:{id:before.id},data:{releaseStatus:status,releaseDecisionAt:new Date(),releaseReason:req.body.reason,version:{increment:1}}});await tx.auditLog.create({data:auditData({userId,entityType:'ProductionBatch',entityId:before.id,action:'update',before,after:updated,reason:req.body.reason,requestId:res.locals.requestId})});return updated;});sendSuccess(res,{...row,warnings:await warnings(row.id)});});}
router.post('/:id/void',validateParams(idSchema),validateBody(decisionSchema),async(req,res)=>{const userId=req.user!.id;const before=await prisma.productionBatch.findFirst({where:{id:req.params.id,userId}});if(!before){sendError(res,ErrorCodes.NOT_FOUND,'Production batch not found',404);return;}const row=await prisma.$transaction(async tx=>{const updated=await tx.productionBatch.update({where:{id:before.id},data:{voidedAt:new Date(),voidReason:req.body.reason,voidedById:userId,version:{increment:1}}});await tx.auditLog.create({data:auditData({userId,entityType:'ProductionBatch',entityId:before.id,action:'void',before,after:updated,reason:req.body.reason,requestId:res.locals.requestId})});return updated;});sendSuccess(res,row);});
export default router;
