'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiariesApi, hivesApi, placementsApi } from '@/lib/api';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import toast from 'react-hot-toast';

export default function MovementsPage(){
 const qc=useQueryClient();const[chosen,setChosen]=useState<string[]>([]);const[toApiaryId,setTarget]=useState('');const[startedAt,setStartedAt]=useState(new Date().toISOString().slice(0,16));const[movementType,setType]=useState('temporary');const[reason,setReason]=useState('');
 const{data:h}=useQuery({queryKey:['hives'],queryFn:()=>hivesApi.list()});const{data:a}=useQuery({queryKey:['apiaries'],queryFn:()=>apiariesApi.list()});const{data:p}=useQuery({queryKey:['placements'],queryFn:()=>placementsApi.list()});
 const move=useMutation({mutationFn:()=>placementsApi.batchMove({hiveIds:chosen,toApiaryId,startedAt:new Date(startedAt).toISOString(),movementType,reason}),onSuccess:()=>{toast.success('Flytting registrert');setChosen([]);qc.invalidateQueries({queryKey:['placements']});qc.invalidateQueries({queryKey:['hives']});},onError:(e:any)=>toast.error(e?.error?.message||'Flytting feilet')});
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Flyttejournal</h1><p className="text-gray-500">Historiske plasseringer bevares som tidsperioder.</p></div><Card><CardContent className="pt-6 space-y-4"><div className="grid md:grid-cols-2 gap-2">{(h?.data||[]).map((x:any)=><label key={x.id} className="border rounded p-3"><input type="checkbox" checked={chosen.includes(x.id)} onChange={e=>setChosen(e.target.checked?[...chosen,x.id]:chosen.filter(id=>id!==x.id))}/> <span className="ml-2">Kube {x.hiveNumber} – {x.apiary?.name}</span></label>)}</div><select className="w-full border rounded p-2" value={toApiaryId} onChange={e=>setTarget(e.target.value)}><option value="">Velg målbigård</option>{(a?.data||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="grid md:grid-cols-2 gap-3"><input className="border rounded p-2" type="datetime-local" value={startedAt} onChange={e=>setStartedAt(e.target.value)}/><select className="border rounded p-2" value={movementType} onChange={e=>setType(e.target.value)}><option value="temporary">Midlertidig</option><option value="permanent">Permanent</option><option value="return">Retur</option><option value="other">Annet</option></select></div><textarea className="w-full border rounded p-2" placeholder="Årsak" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!chosen.length||!toApiaryId||move.isPending} onClick={()=>move.mutate()}>Registrer flytting ({chosen.length})</Button></CardContent></Card><Card><CardContent className="pt-6"><h2 className="font-semibold mb-3">Tidslinje</h2><div className="space-y-2">{(p?.data||[]).map((x:any)=><div key={x.id} className="border-l-4 border-honey-500 pl-3 py-1"><b>{x.apiaryName}</b> · {new Date(x.startedAt).toLocaleString('nb-NO')} – {x.endedAt?new Date(x.endedAt).toLocaleString('nb-NO'):'nå'} · {x.movementType}{x.voidedAt?' (annullert)':''}</div>)}</div></CardContent></Card></div>;
}
